package fr.meritis.prsample.datamodel;

public enum BookType {

    ADVENTURE, CRIME, FABLE, FANTASY, HISTORICAL_FICTION, HORROR, HUMOUR, LITERARY, MYSTERY, POETRY, PLAY, ROMANCE,
    SCIENCE_FICTION, SHORT_STORIES, THRILLER, WAR, YOUNG_ADULT, BIOGRAPHY, AUTOBIOGRAPHY, ESSAY, SELF_HELP
}
